// Title reference patterns are reference grammar, not final templates. AI must
// not do a fixed 12-option selection; patterns may be combined, mutated, and
// extended into multiple variants. They do not provide final coordinates.

export type TitleReferencePatternKey = "stageSplitHero" | "stageMedalTitle" | "businessLaunchHero" | "modernChineseVerticalSeal" | "modernChineseScrollTitle" | "campaignDiagonalImpact" | "campaignTagStack" | "literaryMagazineBlock" | "literaryBookTitle" | "ipPlayfulStack" | "ipBadgeTitle" | "cleanBrandCentered";

export type TitlePatternFamily = "stage" | "business" | "chinese" | "campaign" | "literary" | "ip" | "clean";

export type TitleUnitPattern = "singleHero" | "splitLeadMain" | "threePartStack" | "verticalSeal" | "diagonalSplit" | "editorialBlock" | "badgeLockup";

export type TitlePatternFlexibility = "strict" | "medium" | "loose";

export type TitlePatternCandidateRole = "primary" | "secondary" | "fallback";

export type TitlePatternMutation = "splitUnits" | "mergeUnits" | "resizeUnits" | "moveTitleBox" | "changeOrientation" | "adjustRotation" | "varyDecorationDensity" | "mixWithSecondaryPattern" | "alterUnitEmphasis" | "changeSubtitlePlacement";

export type TitleReferencePattern = {
  label: string; family: TitlePatternFamily; suitableFor: string[]; avoidFor: string[];
  unitPattern: TitleUnitPattern; flexibility: TitlePatternFlexibility; candidateRole: TitlePatternCandidateRole;
  canHybridWith: TitleReferencePatternKey[]; mutationAllowed: TitlePatternMutation[];
  recommendedTitleSplit: string; compositionDescription: string;
  visualTraits: string[]; titleTreatment: string[]; decorationHints: string[]; backgroundFit: string[];
  promptGuidance: string; templateRiskWarning: string;
};

export const TITLE_REFERENCE_PATTERNS: Record<TitleReferencePatternKey, TitleReferencePattern> = {
  stageSplitHero: {
    label: "舞台成果分组标题",
    family: "stage",
    suitableFor: ["成长汇报课", "成果展示", "家长开放日", "教学比赛"],
    avoidFor: ["国学诗词", "正式通知"],
    unitPattern: "splitLeadMain",
    flexibility: "medium",
    candidateRole: "primary",
    canHybridWith: ["stageMedalTitle", "businessLaunchHero", "cleanBrandCentered"],
    mutationAllowed: ["splitUnits", "resizeUnits", "moveTitleBox", "alterUnitEmphasis", "changeSubtitlePlacement", "varyDecorationDensity"],
    recommendedTitleSplit: "将标题拆成前导词和主视觉词，例如：成长 / 汇报课，表达 / 展示，作品 / 发布。",
    compositionDescription: "标题不应只是一整行，应拆成两组。前组略小，后组更大更重，形成舞台主标题的层次。",
    visualTraits: ["舞台感", "成果感", "仪式感", "中心聚光"],
    titleTreatment: ["实心深蓝主字", "轻白描边", "舞台阴影", "暖色光晕"],
    decorationHints: ["smallStars", "medalLine", "stageLight"],
    backgroundFit: ["中部有聚光", "左右有作品墙", "中央有留白"],
    promptGuidance: "生成候选时优先拆成两个字组，让后组成为视觉重心；允许根据背景留白调整字组位置和大小，不要只横排一整行。",
    templateRiskWarning: "不得固定为单一舞台标题模板；必须根据标题语义和背景区域生成多个字组变体。",
  },
  stageMedalTitle: {
    label: "奖章荣誉标题",
    family: "stage",
    suitableFor: ["颁奖", "教学成果", "作品评选", "荣誉展示"],
    avoidFor: ["轻松游园会", "文学杂志感活动"],
    unitPattern: "badgeLockup",
    flexibility: "medium",
    candidateRole: "secondary",
    canHybridWith: ["stageSplitHero", "businessLaunchHero"],
    mutationAllowed: ["splitUnits", "resizeUnits", "varyDecorationDensity", "mixWithSecondaryPattern", "alterUnitEmphasis"],
    recommendedTitleSplit: "将荣誉词、主题词分开，例如：优秀 / 作品展，成长 / 星光榜。",
    compositionDescription: "标题可以和奖章、星光、荣誉线条形成组合，像一个荣誉标识。",
    visualTraits: ["荣誉感", "金色辅助", "对称构图", "稳重"],
    titleTreatment: ["厚重字体", "金色细线", "深蓝主字", "局部星光"],
    decorationHints: ["medalLine", "smallStars", "goldLine"],
    backgroundFit: ["舞台", "展陈空间", "奖杯奖章元素"],
    promptGuidance: "标题要像荣誉标识，而不是普通活动标题；可与 stageSplitHero 混合形成更强成果感。",
    templateRiskWarning: "不得把奖章元素固定贴在每张成果图上；只有活动语义明确有荣誉感时才作为主参考。",
  },
  businessLaunchHero: {
    label: "商务发布会大标题",
    family: "business",
    suitableFor: ["公司活动", "周年庆", "课程发布", "品牌会议"],
    avoidFor: ["低龄活动", "国风诗词"],
    unitPattern: "singleHero",
    flexibility: "medium",
    candidateRole: "primary",
    canHybridWith: ["stageSplitHero", "stageMedalTitle", "cleanBrandCentered"],
    mutationAllowed: ["splitUnits", "resizeUnits", "moveTitleBox", "alterUnitEmphasis", "varyDecorationDensity"],
    recommendedTitleSplit: "如果标题较短可保持整体；如果较长则拆为数字 / 主题 / 发布词。",
    compositionDescription: "标题应有发布会 KV 的正式感，主标题集中、厚重、品牌化。",
    visualTraits: ["发布会", "品牌色块", "数字纪念", "商务光效"],
    titleTreatment: ["粗黑体", "深蓝主色", "橙红辅助", "轻微立体阴影"],
    decorationHints: ["brandBlock", "stageLight", "numericBadge"],
    backgroundFit: ["深色舞台", "品牌光效", "横向发布构图"],
    promptGuidance: "标题要像发布会主 KV，不要像普通通知；允许和 stageSplitHero 混合增强仪式感。",
    templateRiskWarning: "不得固定为居中大字；必须根据发布主题、数字纪念或品牌事件调整标题结构。",
  },
  modernChineseVerticalSeal: {
    label: "现代国风竖排题签",
    family: "chinese",
    suitableFor: ["国学", "诗词", "名著", "传统文化"],
    avoidFor: ["招生冲刺", "强营销"],
    unitPattern: "verticalSeal",
    flexibility: "medium",
    candidateRole: "primary",
    canHybridWith: ["modernChineseScrollTitle", "literaryMagazineBlock"],
    mutationAllowed: ["splitUnits", "resizeUnits", "moveTitleBox", "changeOrientation", "alterUnitEmphasis", "varyDecorationDensity"],
    recommendedTitleSplit: "优先拆为两个竖排字组，例如：国学 / 少年说，诗词 / 启蒙。",
    compositionDescription: "标题像现代题签或印章化标题，竖排字组要有层级，不是一列字机械排下去。",
    visualTraits: ["国风", "题签", "留白", "文化感"],
    titleTreatment: ["宋体或楷体骨架", "米白描边", "深蓝或墨色", "红金辅助"],
    decorationHints: ["sealStamp", "goldLine", "cloudPattern", "paperTag"],
    backgroundFit: ["山水", "卷轴", "月亮", "古典建筑", "大面积留白"],
    promptGuidance: "竖排时必须拆成字组，避免整句一列到底；可让主字组更大、更靠视觉中心。",
    templateRiskWarning: "不得把国风标题固定成一列竖字；竖排只是语法之一，必须根据留白和主题决定。",
  },
  modernChineseScrollTitle: {
    label: "国风卷轴横题",
    family: "chinese",
    suitableFor: ["四大名著", "传统文化活动", "读书节国风版"],
    avoidFor: ["科技感", "强营销"],
    unitPattern: "splitLeadMain",
    flexibility: "medium",
    candidateRole: "secondary",
    canHybridWith: ["modernChineseVerticalSeal", "literaryMagazineBlock"],
    mutationAllowed: ["splitUnits", "resizeUnits", "moveTitleBox", "changeOrientation", "mixWithSecondaryPattern", "varyDecorationDensity"],
    recommendedTitleSplit: "可拆为文化主题词和活动词，例如：四大名著 / 少年说。",
    compositionDescription: "标题可横向放在卷轴、题签或留白区域中，保持现代国风，不做廉价毛笔字。",
    visualTraits: ["卷轴", "金线", "章回小说感", "文化空间"],
    titleTreatment: ["宋体", "金色细线", "红色小印章", "克制阴影"],
    decorationHints: ["scrollLine", "sealStamp", "goldLine"],
    backgroundFit: ["卷轴构图", "山水留白", "古典建筑"],
    promptGuidance: "标题应像现代文化活动 KV，不要像古风游戏字；可和竖排题签混合生成候选。",
    templateRiskWarning: "不得固定为卷轴横幅；只有背景语境支持卷轴或题签时才强化。",
  },
  campaignDiagonalImpact: {
    label: "强营销斜切冲击标题",
    family: "campaign",
    suitableFor: ["招生", "报名提醒", "开班提醒", "短期活动"],
    avoidFor: ["品牌理念", "高级留白"],
    unitPattern: "diagonalSplit",
    flexibility: "loose",
    candidateRole: "primary",
    canHybridWith: ["campaignTagStack", "businessLaunchHero"],
    mutationAllowed: ["splitUnits", "resizeUnits", "moveTitleBox", "adjustRotation", "alterUnitEmphasis", "varyDecorationDensity", "mixWithSecondaryPattern"],
    recommendedTitleSplit: "拆成时间 / 对象 / 动作，例如：春季 / 新班 / 招生，暑假 / 文学营。",
    compositionDescription: "标题应形成强动势，不是一整行斜着放。关键词要更大，形成视觉冲击。",
    visualTraits: ["高对比", "动势", "转化导向", "抓眼"],
    titleTreatment: ["粗展示字体", "白描边", "强阴影", "品牌色块"],
    decorationHints: ["campaignLabel", "growthArrow", "colorBlock"],
    backgroundFit: ["斜向动线", "成长路径", "强色块", "招生信息区"],
    promptGuidance: "必须拆成多个字组，关键词更大；不要只是整句旋转。",
    templateRiskWarning: "不得为了变化而斜排；斜切必须服务动势、转化和视觉引导。",
  },
  campaignTagStack: {
    label: "活动标签堆叠标题",
    family: "campaign",
    suitableFor: ["开班提醒", "报名提醒", "限时活动"],
    avoidFor: ["国学", "文学杂志"],
    unitPattern: "threePartStack",
    flexibility: "loose",
    candidateRole: "secondary",
    canHybridWith: ["campaignDiagonalImpact", "ipBadgeTitle"],
    mutationAllowed: ["splitUnits", "resizeUnits", "moveTitleBox", "alterUnitEmphasis", "varyDecorationDensity", "mixWithSecondaryPattern"],
    recommendedTitleSplit: "可拆成三段，例如：春季 / 新班 / 招生，限时 / 体验 / 报名。",
    compositionDescription: "标题像多个活动标签堆叠，强调行动感。",
    visualTraits: ["标签感", "色块", "强层级", "明确转化"],
    titleTreatment: ["粗字", "强描边", "色块底托", "关键词放大"],
    decorationHints: ["campaignLabel", "colorBlock", "arrow"],
    backgroundFit: ["强营销背景", "大留白", "活动色块"],
    promptGuidance: "标题可以像标签组合，不要像普通公告文字；可和斜切冲击标题混合。",
    templateRiskWarning: "不得变成固定标签模板；标签数量和大小必须根据标题语义生成。",
  },
  literaryMagazineBlock: {
    label: "文学杂志封面标题",
    family: "literary",
    suitableFor: ["一本好书", "读书节", "文学周", "品牌理念"],
    avoidFor: ["强营销", "低龄游园会"],
    unitPattern: "editorialBlock",
    flexibility: "medium",
    candidateRole: "primary",
    canHybridWith: ["literaryBookTitle", "modernChineseScrollTitle"],
    mutationAllowed: ["splitUnits", "resizeUnits", "moveTitleBox", "changeSubtitlePlacement", "alterUnitEmphasis"],
    recommendedTitleSplit: "短标题可保持整体，长标题拆为主题词和说明词。",
    compositionDescription: "标题像杂志封面标题，有编辑感、留白和文字层级。",
    visualTraits: ["杂志感", "书卷气", "克制", "留白"],
    titleTreatment: ["文楷或宋体", "大字距", "轻阴影", "纸张质感"],
    decorationHints: ["bookMark", "paperTag", "thinLine"],
    backgroundFit: ["书页", "阅读灯光", "纸张层次", "文学空间"],
    promptGuidance: "标题要像编辑设计，不要像小清新手账；可生成克制但有层级的候选。",
    templateRiskWarning: "不得固定成杂志封面模板；编辑感来自层级和留白，不是固定位置。",
  },
  literaryBookTitle: {
    label: "书名式标题",
    family: "literary",
    suitableFor: ["一本好书", "阅读活动", "书单推荐"],
    avoidFor: ["招生冲刺", "发布会"],
    unitPattern: "singleHero",
    flexibility: "medium",
    candidateRole: "secondary",
    canHybridWith: ["literaryMagazineBlock", "cleanBrandCentered"],
    mutationAllowed: ["resizeUnits", "moveTitleBox", "changeSubtitlePlacement", "varyDecorationDensity"],
    recommendedTitleSplit: "标题可像书名一样集中处理，副标题作为小字说明。",
    compositionDescription: "标题像一本书的封面主标题，安静但有识别度。",
    visualTraits: ["书名感", "温和", "阅读感", "品牌气质"],
    titleTreatment: ["文楷", "轻描边", "低饱和阴影", "纸张纹理"],
    decorationHints: ["bookMark", "paperFold"],
    backgroundFit: ["图书馆", "书页", "阅读空间"],
    promptGuidance: "标题要安静但有存在感，不要被背景吞掉。",
    templateRiskWarning: "不得把所有阅读活动都变成书名封面；只在标题语义适合时使用。",
  },
  ipPlayfulStack: {
    label: "IP 活动错落标题",
    family: "ip",
    suitableFor: ["暑期营", "游园会", "轻活动", "儿童互动"],
    avoidFor: ["正式发布会", "高级国风"],
    unitPattern: "threePartStack",
    flexibility: "loose",
    candidateRole: "primary",
    canHybridWith: ["ipBadgeTitle", "campaignTagStack"],
    mutationAllowed: ["splitUnits", "resizeUnits", "moveTitleBox", "adjustRotation", "alterUnitEmphasis", "varyDecorationDensity", "mixWithSecondaryPattern"],
    recommendedTitleSplit: "可拆为活动名的自然语义组，例如：暑期 / 文学营，诗词 / 游园会。",
    compositionDescription: "标题可以上下错落，有轻微动势，但不能低幼廉价。",
    visualTraits: ["活泼", "轻卡通", "品牌 IP 感", "趣味"],
    titleTreatment: ["漫黑或圆体", "白描边", "柔和阴影", "小图标辅助"],
    decorationHints: ["smallStars", "bookMark", "playfulDot"],
    backgroundFit: ["活动道具", "游戏场景", "IP 氛围"],
    promptGuidance: "错落要有节奏，不要把字随便散开。",
    templateRiskWarning: "不得为了活泼而散乱；错落必须有阅读顺序和视觉节奏。",
  },
  ipBadgeTitle: {
    label: "IP 徽章标题",
    family: "ip",
    suitableFor: ["节日活动", "轻活动", "打卡图"],
    avoidFor: ["严肃比赛", "公司发布"],
    unitPattern: "badgeLockup",
    flexibility: "medium",
    candidateRole: "secondary",
    canHybridWith: ["ipPlayfulStack", "campaignTagStack"],
    mutationAllowed: ["splitUnits", "resizeUnits", "moveTitleBox", "varyDecorationDensity", "mixWithSecondaryPattern"],
    recommendedTitleSplit: "短标题可做徽章整体，长标题拆成主词和活动词。",
    compositionDescription: "标题像一个可识别活动徽章，适合社群传播。",
    visualTraits: ["徽章", "圆角", "趣味", "亲和"],
    titleTreatment: ["圆体", "强可读", "活动色块", "小装饰"],
    decorationHints: ["badge", "smallStars", "playfulDot"],
    backgroundFit: ["IP 活动", "节日", "打卡"],
    promptGuidance: "标题像活动徽章，不要像普通横幅。",
    templateRiskWarning: "不得固定成同一个徽章样式；徽章形态必须根据活动主题变化。",
  },
  cleanBrandCentered: {
    label: "品牌清晰居中标题",
    family: "clean",
    suitableFor: ["通知", "课程说明", "家长群", "正式说明图"],
    avoidFor: ["强视觉活动", "需要标题强记忆点的主视觉"],
    unitPattern: "singleHero",
    flexibility: "strict",
    candidateRole: "fallback",
    canHybridWith: ["businessLaunchHero", "literaryBookTitle"],
    mutationAllowed: ["resizeUnits", "moveTitleBox", "changeSubtitlePlacement"],
    recommendedTitleSplit: "一般不拆，保持清楚。",
    compositionDescription: "标题居中、清楚、可信，信息优先。",
    visualTraits: ["清楚", "稳定", "品牌一致", "高可读"],
    titleTreatment: ["思源黑体", "克制阴影", "不做复杂装饰"],
    decorationHints: ["none"],
    backgroundFit: ["高级留白", "通知图", "说明图"],
    promptGuidance: "这是保底模式，不应用于追求强设计感的主视觉。",
    templateRiskWarning: "不得把 cleanBrandCentered 当作所有图的默认答案；它只用于信息优先和保底场景。",
  },
};
