import type { YuanfangStyleTreatment, YuanfangStyleTreatmentKey } from "@/models/yuanfang-visual-rules";

function styleTreatment(input: YuanfangStyleTreatment): YuanfangStyleTreatment {
  return input;
}

export const YUANFANG_STYLE_TREATMENTS: Record<YuanfangStyleTreatmentKey, YuanfangStyleTreatment> = {
  brandKineticKV: styleTreatment({ key: "brandKineticKV", label: "品牌发布动势 KV", suitableFamilies: ["brandEvent", "companyActivity"], promptGuidance: "Use brand-color kinetic curves, stage light, deep-blue/orange contrast, and launch-event energy.", colorEnergy: "deep blue with orange/red highlights, high contrast but warm", motifTreatment: "brand ribbons, light beams, course-upgrade path, stage depth", avoid: ["soft pastel illustration", "empty beige board", "nightclub look"] }),
  boldEnrollmentCampaign: styleTreatment({ key: "boldEnrollmentCampaign", label: "强招生活动视觉", suitableFamilies: ["enrollment", "openClass"], promptGuidance: "Use bolder blocks, campaign rhythm, course-value symbols, and conversion energy without cheap promo styling.", colorEnergy: "bright brand palette with controlled contrast", motifTreatment: "growth path, course module, strong theme symbol, energetic frame", avoid: ["low-end sales poster", "tiny hook decoration", "plain education wallpaper"] }),
  literaryEditorialCollage: styleTreatment({ key: "literaryEditorialCollage", label: "文学编辑拼贴", suitableFamilies: ["literaryActivity", "openClass", "enrollment"], promptGuidance: "Use fresh reading-course collage, books, lamps, character/IP participation, modern blue-white/green accents, and campaign rhythm rather than guofeng by default.", colorEnergy: "blue-white, fresh green, warm yellow, restrained orange accents", motifTreatment: "book world, course scene, reading lamp, character silhouettes, playful literary symbols without text", avoid: ["single open-book template", "blank paper slab", "stock library illustration", "default ink landscape"] }),
  modernGuofengInk: styleTreatment({ key: "modernGuofengInk", label: "现代国风水墨", suitableFamilies: ["guofengLiterature", "poetryFestival"], promptGuidance: "Use modern guofeng only for explicit poetry, classical culture, festival literature, or traditional-culture briefs; keep it lively and contemporary, not default reading style.", colorEnergy: "cyan-green, warm paper, deep blue, restrained cinnabar", motifTreatment: "scroll, ink layers, poetic plants, mountains, classical architecture, literary scene", avoid: ["old-fashioned red-gold", "game-like fantasy costume", "fake calligraphy text", "generic reading wallpaper"] }),
  warmAchievementStage: styleTreatment({ key: "warmAchievementStage", label: "温暖成果舞台", suitableFamilies: ["achievementShowcase"], promptGuidance: "Use warm stage light, works wall, podium, microphone, award accents, and parent-witness ceremony.", colorEnergy: "warm gold, sky blue, orange, soft deep blue", motifTreatment: "stage spotlight with texture, works display, growth path, expression symbols", avoid: ["commercial concert", "overblank spotlight column", "messy wall text"] }),
  campusHonorFormal: styleTreatment({ key: "campusHonorFormal", label: "校区荣誉正式风", suitableFamilies: ["campusActivity", "teachingCompetition"], promptGuidance: "Use formal campus honor, teaching podium, exhibition wall, award geometry, and professional education atmosphere.", colorEnergy: "deep blue, warm gold, clean white, measured brand accents", motifTreatment: "podium, honor badge, teaching display, campus stage, structured side walls", avoid: ["variety-show competition", "trophy pile", "generic award background"] }),
  techBlueLearning: styleTreatment({ key: "techBlueLearning", label: "蓝色科技学习风", suitableFamilies: ["openClass", "enrollment", "brandEvent"], promptGuidance: "Use blue learning technology, clean data-like arcs, course modules, and warm education cues, not cold SaaS screens.", colorEnergy: "deep blue, sky blue, white, small orange/green accents", motifTreatment: "AI learning path, writing flow, modular panels, light grid without text", avoid: ["cold enterprise SaaS", "fake UI text", "robot mascot"] }),
  premiumMinimalNotice: styleTreatment({ key: "premiumMinimalNotice", label: "高级轻通知", suitableFamilies: ["campusActivity", "brandEvent", "literaryActivity"], promptGuidance: "Use premium minimal structure with tactile paper/light/color blocks; leave readable zones with designed texture, not blank templates.", colorEnergy: "light warm neutrals with one or two Yuanfang accents", motifTreatment: "subtle brand geometry, paper depth, quiet motif, calm hierarchy", avoid: ["pure blank page", "generic beige poster", "no theme memory point"] }),
};
